#!/usr/bin/env bash
set -euo pipefail

if ! command -v gcloud >/dev/null 2>&1; then
  echo "gcloud CLI is required."
  exit 1
fi

PROJECT_ID="${PROJECT_ID:?Set PROJECT_ID (e.g. my-gcp-project)}"
REGION="${REGION:-us-central1}"
TAG="${TAG:-$(date +%Y%m%d-%H%M%S)}"

BACKEND_SERVICE="${BACKEND_SERVICE:-learner-compass-backend}"
FRONTEND_SERVICE="${FRONTEND_SERVICE:-learner-compass-frontend}"

BACKEND_IMAGE="gcr.io/${PROJECT_ID}/${BACKEND_SERVICE}:${TAG}"
FRONTEND_IMAGE="gcr.io/${PROJECT_ID}/${FRONTEND_SERVICE}:${TAG}"

BACKEND_MIN_INSTANCES="${BACKEND_MIN_INSTANCES:-1}"
BACKEND_MAX_INSTANCES="${BACKEND_MAX_INSTANCES:-50}"
BACKEND_CONCURRENCY="${BACKEND_CONCURRENCY:-200}"
RATE_LIMIT_MAX_PER_MINUTE="${RATE_LIMIT_MAX_PER_MINUTE:-300}"
MAX_SEARCH_RESULTS="${MAX_SEARCH_RESULTS:-50}"
SEARCH_CACHE_TTL_MS="${SEARCH_CACHE_TTL_MS:-30000}"
SEARCH_CACHE_MAX_ENTRIES="${SEARCH_CACHE_MAX_ENTRIES:-2000}"
CODE_EXEC_PROVIDER="${CODE_EXEC_PROVIDER:-judge0}"
CODE_EXEC_API_URL="${CODE_EXEC_API_URL:-}"
CODE_EXEC_API_KEY="${CODE_EXEC_API_KEY:-}"
CODE_EXEC_API_HOST="${CODE_EXEC_API_HOST:-judge0-ce.p.rapidapi.com}"
CODE_EXEC_REQUEST_TIMEOUT_MS="${CODE_EXEC_REQUEST_TIMEOUT_MS:-12000}"
CODE_EXEC_POLL_INTERVAL_MS="${CODE_EXEC_POLL_INTERVAL_MS:-700}"
CODE_EXEC_POLL_ATTEMPTS="${CODE_EXEC_POLL_ATTEMPTS:-20}"
CODE_EXEC_MAX_TEST_CASES="${CODE_EXEC_MAX_TEST_CASES:-20}"
CODE_EXEC_MAX_SOURCE_CHARS="${CODE_EXEC_MAX_SOURCE_CHARS:-20000}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
OPENAI_API_URL="${OPENAI_API_URL:-https://api.openai.com/v1}"
OPENAI_MODEL="${OPENAI_MODEL:-gpt-4.1-mini}"
OPENAI_REQUEST_TIMEOUT_MS="${OPENAI_REQUEST_TIMEOUT_MS:-18000}"
OPENAI_MAX_CONTEXT_CHARS="${OPENAI_MAX_CONTEXT_CHARS:-12000}"
YOUTUBE_API_KEY="${YOUTUBE_API_KEY:-}"
YOUTUBE_API_URL="${YOUTUBE_API_URL:-https://www.googleapis.com/youtube/v3}"
YOUTUBE_DEFAULT_MAX_RESULTS="${YOUTUBE_DEFAULT_MAX_RESULTS:-6}"
YOUTUBE_REQUEST_TIMEOUT_MS="${YOUTUBE_REQUEST_TIMEOUT_MS:-10000}"

FRONTEND_MIN_INSTANCES="${FRONTEND_MIN_INSTANCES:-1}"
FRONTEND_MAX_INSTANCES="${FRONTEND_MAX_INSTANCES:-20}"
FRONTEND_CONCURRENCY="${FRONTEND_CONCURRENCY:-200}"

echo "Deploying backend image: ${BACKEND_IMAGE}"
gcloud builds submit \
  --project "${PROJECT_ID}" \
  --config deploy/cloudrun/cloudbuild.backend.yaml \
  --substitutions "_IMAGE=${BACKEND_IMAGE}" \
  .

gcloud run deploy "${BACKEND_SERVICE}" \
  --project "${PROJECT_ID}" \
  --region "${REGION}" \
  --image "${BACKEND_IMAGE}" \
  --platform managed \
  --allow-unauthenticated \
  --port 4000 \
  --min-instances "${BACKEND_MIN_INSTANCES}" \
  --max-instances "${BACKEND_MAX_INSTANCES}" \
  --concurrency "${BACKEND_CONCURRENCY}" \
  --cpu 1 \
  --memory 512Mi \
  --set-env-vars "NODE_ENV=production,HOST=0.0.0.0,PORT=4000,RATE_LIMIT_MAX_PER_MINUTE=${RATE_LIMIT_MAX_PER_MINUTE},MAX_SEARCH_RESULTS=${MAX_SEARCH_RESULTS},SEARCH_CACHE_TTL_MS=${SEARCH_CACHE_TTL_MS},SEARCH_CACHE_MAX_ENTRIES=${SEARCH_CACHE_MAX_ENTRIES},CODE_EXEC_PROVIDER=${CODE_EXEC_PROVIDER},CODE_EXEC_API_URL=${CODE_EXEC_API_URL},CODE_EXEC_API_HOST=${CODE_EXEC_API_HOST},CODE_EXEC_REQUEST_TIMEOUT_MS=${CODE_EXEC_REQUEST_TIMEOUT_MS},CODE_EXEC_POLL_INTERVAL_MS=${CODE_EXEC_POLL_INTERVAL_MS},CODE_EXEC_POLL_ATTEMPTS=${CODE_EXEC_POLL_ATTEMPTS},CODE_EXEC_MAX_TEST_CASES=${CODE_EXEC_MAX_TEST_CASES},CODE_EXEC_MAX_SOURCE_CHARS=${CODE_EXEC_MAX_SOURCE_CHARS},OPENAI_API_URL=${OPENAI_API_URL},OPENAI_MODEL=${OPENAI_MODEL},OPENAI_REQUEST_TIMEOUT_MS=${OPENAI_REQUEST_TIMEOUT_MS},OPENAI_MAX_CONTEXT_CHARS=${OPENAI_MAX_CONTEXT_CHARS},YOUTUBE_API_URL=${YOUTUBE_API_URL},YOUTUBE_DEFAULT_MAX_RESULTS=${YOUTUBE_DEFAULT_MAX_RESULTS},YOUTUBE_REQUEST_TIMEOUT_MS=${YOUTUBE_REQUEST_TIMEOUT_MS}${REDIS_URL:+,REDIS_URL=${REDIS_URL}}${CODE_EXEC_API_KEY:+,CODE_EXEC_API_KEY=${CODE_EXEC_API_KEY}}${OPENAI_API_KEY:+,OPENAI_API_KEY=${OPENAI_API_KEY}}${YOUTUBE_API_KEY:+,YOUTUBE_API_KEY=${YOUTUBE_API_KEY}}"

BACKEND_URL="$(gcloud run services describe "${BACKEND_SERVICE}" --project "${PROJECT_ID}" --region "${REGION}" --format='value(status.url)')"
echo "Backend URL: ${BACKEND_URL}"

echo "Deploying frontend image: ${FRONTEND_IMAGE}"
gcloud builds submit \
  --project "${PROJECT_ID}" \
  --config deploy/cloudrun/cloudbuild.frontend.yaml \
  --substitutions "_IMAGE=${FRONTEND_IMAGE},_VITE_API_BASE_URL=${BACKEND_URL}" \
  .

gcloud run deploy "${FRONTEND_SERVICE}" \
  --project "${PROJECT_ID}" \
  --region "${REGION}" \
  --image "${FRONTEND_IMAGE}" \
  --platform managed \
  --allow-unauthenticated \
  --port 80 \
  --min-instances "${FRONTEND_MIN_INSTANCES}" \
  --max-instances "${FRONTEND_MAX_INSTANCES}" \
  --concurrency "${FRONTEND_CONCURRENCY}" \
  --cpu 1 \
  --memory 512Mi

FRONTEND_URL="$(gcloud run services describe "${FRONTEND_SERVICE}" --project "${PROJECT_ID}" --region "${REGION}" --format='value(status.url)')"
echo "Frontend URL: ${FRONTEND_URL}"
echo "Deployment complete."
